name: flutter_scada
description: "Professional SCADA System - Industrial Control & Monitoring"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  mqtt_client: ^10.0.0
  collection: ^1.18.0
  intl: ^0.18.1
  uuid: ^4.3.3
  dio_cookie_manager: ^2.1.0
  cookie_jar: ^3.0.1
  path_provider: ^2.1.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
